export const GET_ALL_CATEGORY = "GET_ALL_CATEGORY";

export const GET_ERROR = "GET_ERROR";

export const CREATE_SUB_CATEGORY = "CREATE_SUB_CATEGORY";

export const CREATE_CATEGORY = "CREATE_CATEGORY";

export const GET_ALL_BRAND = "GET_ALL_BRAND";

export const CREATE_BRAND = "CREATE_BRAND";

export const GET_SUB_CATEGORY = "GET_SUB_CATEGORY";

export const CREATE_PRODUCTS = "CREATE_PRODUCTS";

export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";

export const GET_PRODUCT_DETAILS = "GET_PRODUCT_DETAILS";

export const GET_ONE_CATEGORY = "GET_ONE_CATEGORY";

export const GET_ONE_BRAND = " GET_ONE_BRAND";

export const GET_PRODUCT_LIKE = "GET_PRODUCT_LIKE";

export const DELETE_PRODUCT = "DELETE_PRODUCT";

export const UPDATE_PRODUCT = "UPDATE_PRODUCT";

export const CREATE_NEW_USER = "CREATE_NEW_USER";

export const LOGIN_USER = "LOGIN_USER";

export const FORGET_PASSWORD = "FORGET_PASSWORD";

export const VERIFY_OTP = "VERIFY_OTP";

export const RESET_PASSWORD = "RESET_PASSWORD";

export const GET_SUB_CATEGORY_PRODUCTS = "GET_SUB_CATEGORY_PRODUCTS";

// export const GET_CURRENT_USER = "GET_CURRENT_USER";

export const CREATE_REVIEW = "CREATE_REVIEW";

export const GET_ONE_REVIEW_TO_ONE_PRODUCT = "GET_ONE_REVIEW_TO_ONE_PRODUCT";

export const DELETE_REVIEW = "DELETE_REVIEW";

export const UPDATE_REVIEW = "UPDATE_REVIEW";

export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST";

export const REMOVE_WISHLIST = "REMOVE_WISHLIST";

export const GET_USER_WISHLIST = "GET_USER_WISHLIST";

export const ADD_COUPONS = "ADD_COUPONS";

export const GET_ALL_COUPONS = "GET_ALL_COUPONS";

export const DELETE_COUPONS = "DELETE_COUPONS";

export const GET_ONE_COUPONS = "GET_ONE_COUPONS";

export const EDIT_COUPONS = "EDIT_COUPONS";

export const ADD_USER_ADDRESS = "ADD_USER_ADDRESS";

export const GET_ALL_USER_ADDRESS = "GET_ALL_USER_ADDRESS";

export const DELETE_USER_ADDRESS = "DELETE_USER_ADDRESS";

export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";

export const GET_ALL_USER_CART_ITEMS = "GET_ALL_USER_CART_ITEMS";

export const CLEAR_ALL_USER_CART_ITEMS = "CLEAR_ALL_USER_CART_ITEMS";

export const DELETE_ONE_CART_ITEMS = "DELETE_ONE_CART_ITEMS";

export const UPDATE_CART_ITEMS = "UPDATE_CART_ITEMS";

export const APPLY_COUPON_TO_CART = "APPLY_COUPON_TO_CART";

export const GET_ALL_PRODUCTS_BY_CATEGORY = "GET_ALL_PRODUCTS_BY_CATEGORY";

export const GET_ALL_PRODUCTS_BY_BRAND = "GET_ALL_PRODUCTS_BY_BRAND";

export const UPDATE_PROFILE_DATA = "UPDATE_PROFILE_DATA";

export const UPDATE_PROFILE_PASSWORD = "UPDATE_PROFILE_PASSWORD";

export const GET_ONE_USER_ADDRESS = "GET_ONE_USER_ADDRESS";

export const UPDATE_USER_ADDRESS = "UPDATE_USER_ADDRESS";

export const CREATE_ORDER_CASH = "CREATE_ORDER_CASH";

export const GET_ALL_ORDERS = "GET_ALL_ORDERS";

export const GET_ONE_ORDER = "GET_ONE_ORDER";

export const UPDATE_ORDER_TO_PAY = "UPDATE_ORDER_TO_PAY";

export const UPDATE_ORDER_TO_DELIVER = "UPDATE_ORDER_TO_DELIVER";

export const CREATE_ORDER_BY_CARD = "CREATE_ORDER_BY_CARD";

// auction
export const CREATE_NEW_EVENTS = "CREATE_NEW_EVENTS";

export const GET_ALL_EVENTS = "GET_ALL_EVENTS";

export const GET_LOGGED_USER = "GET_LOGGED_USER";

export const CREATE_PRODUCTS_AUCTION = "CREATE_PRODUCTS_AUCTION";
